<a href="https://colab.research.google.com/github/Imrantipu/-serviceReviewServer/blob/main/Pytorch_nn_moduel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)
      return out


In [2]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
#model.forward(features)
model(features)  # magic method to call forward method inside Model class

tensor([[0.5696],
        [0.6152],
        [0.5610],
        [0.6238],
        [0.5529],
        [0.5623],
        [0.5220],
        [0.5684],
        [0.5570],
        [0.5614]], grad_fn=<SigmoidBackward0>)

In [3]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0888,  0.2946, -0.2656,  0.0751, -0.1357]], requires_grad=True)

In [4]:
#show model bias
model.linear.bias

Parameter containing:
tensor([0.3282], requires_grad=True)

In [5]:
#for visualizing the network
!pip install torchinfo



In [7]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00