<a href="https://colab.research.google.com/github/Imrantipu/-serviceReviewServer/blob/main/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.version.cuda)


2.5.1+cu121
False
12.1


#Creating a Tensor

In [2]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[4.2039e-45, 8.4078e-45, 4.2039e-45],
        [9.8091e-45, 1.5835e-42, 4.3754e-41]])


In [3]:
# check type
print(a.dtype)
type(a)

torch.float32


torch.Tensor

In [4]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# using rand generates 0-1 float values
torch.rand(2,3)

tensor([[0.8549, 0.4118, 0.5696],
        [0.9330, 0.2929, 0.4805]])

In [7]:
# use of seed for same random values again
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
# using tensor for custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
from math import prod
# Other ways
# arange
print("using arange ->", torch.arange(0,10,2))
#using linspace
print("using linspace ->", torch.linspace(0,10,10))
# using eye for identity matrix
print("using eye ->", torch.eye(5))
#using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor shapes

In [10]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

torch.Size([2, 3])


In [11]:
# produce tensor like same shape of  existing one
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3559307581643318067]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Tensor data type

In [15]:
# find data type
x.dtype

torch.int64

In [16]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [17]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathmatical operation

##1.Scaler operation

In [18]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [19]:
#addition
x+2
# substraction
x-2
# multiplication
x*2
# division
x/2
# int division
x//2
# power
x**2
#mod
x%2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

##2. Element wise operation

In [20]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [21]:
# add
a + b
# sustraction
a -b
# multiplication
a**b
# division
a/b
# power
a**b
# mod
a%b


tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [22]:
c = torch.tensor([1,-2,3,-4])

In [23]:
# absulute
torch.abs(c)

tensor([1, 2, 3, 4])

In [24]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [25]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [26]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [27]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [28]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [29]:
# less then 2 will be 2 and bigger then 3 will be 3
torch.clamp(d,min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

##3. Reduction operation

In [30]:
e = torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)
print(e)

tensor([[8., 0., 7.],
        [0., 0., 9.]])


In [31]:
# sum
torch.sum(e)

tensor(24.)

In [32]:
# sum along columns
torch.sum(e, dim = 0)

tensor([ 8.,  0., 16.])

In [33]:
#sum along rows
torch.sum(e, dim = 1)

tensor([15.,  9.])

In [34]:
#mean
torch.mean(e)

tensor(4.)

In [35]:
# mean along columns
torch.mean(e, dim = 0)

tensor([4., 0., 8.])

In [36]:
# median
torch.median(e)

tensor(0.)

In [37]:
# max
torch.max(e)

tensor(9.)

In [38]:
#min
torch.min(e)

tensor(0.)

In [39]:
# Product
torch.prod(e)

tensor(0.)

In [40]:
# variance
torch.var(e)

tensor(19.6000)

In [41]:
# stardard deviation
torch.std(e)

tensor(4.4272)

In [42]:
#argmax for maximum value position
torch.argmax(e)

tensor(5)

In [43]:
# argmin
torch.argmin(e)

tensor(1)

##4. Matrix operation

In [44]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [46]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [47]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
# dot product
torch.dot(vector1,vector2)

tensor(11)

In [50]:
# transpose
print(f)
torch.transpose(f,0,1)

tensor([[5, 7, 3],
        [9, 4, 0]])


tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [51]:
h = torch.randint(size=(3,3), low =0, high=10, dtype=torch.float32)
print(h)

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])


In [52]:
#determinant
torch.det(h)

tensor(-110.)

In [53]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

##5.Comparison operations

In [54]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [56]:
# grater then
print(i > j)
# less then
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)



tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


##6. Special function

In [64]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])


In [59]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [60]:
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [61]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [62]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [65]:
torch.softmax(k, dim = 0) # for columns

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [66]:
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Inplace operation

In [67]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [71]:
# after operation result store in one operand
print(m.add_(n)) # permanent change happend in m
n.relu_() # permanent change happend in n


tensor([[1.6341, 1.0045, 4.6169],
        [3.3943, 0.6739, 2.7089]])


tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

## copy a tensor

In [73]:
a = torch.rand(2,3)
print(a)

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [77]:
b = a.clone()
print(b)

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])
