<a href="https://colab.research.google.com/github/Imrantipu/-serviceReviewServer/blob/main/tensor_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


#Reshaping tensors

In [3]:
a = torch.ones(4,4)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [4]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [6]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b = torch.rand(2,3,4)
print(b)

tensor([[[0.6144, 0.3734, 0.0023, 0.3209],
         [0.1896, 0.3362, 0.9907, 0.1404],
         [0.0219, 0.0235, 0.8702, 0.8362]],

        [[0.5645, 0.8349, 0.8029, 0.5011],
         [0.0942, 0.9697, 0.5569, 0.2971],
         [0.8449, 0.0252, 0.3873, 0.1308]]])


In [9]:
# Permute changes the matrix indixes (2,3,4), indixes will be (0,1,2)
print(b.permute(2,0,1).shape)
b.permute(2,0,1)


torch.Size([4, 2, 3])


tensor([[[0.6144, 0.1896, 0.0219],
         [0.5645, 0.0942, 0.8449]],

        [[0.3734, 0.3362, 0.0235],
         [0.8349, 0.9697, 0.0252]],

        [[0.0023, 0.9907, 0.8702],
         [0.8029, 0.5569, 0.3873]],

        [[0.3209, 0.1404, 0.8362],
         [0.5011, 0.2971, 0.1308]]])

In [10]:
#unsqueeze for adding new dimentions
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape #other place like 1 ,2 rater than 0 we can use

torch.Size([1, 226, 226, 3])

In [11]:
#squeeze for taking out ne dimention
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

#numpy and pytorch tensors moving

In [15]:
import numpy as np

a = torch.tensor([1,2,3])
print(a)
type(a)

tensor([1, 2, 3])


torch.Tensor

In [16]:
b = a.numpy()
print(b)
type(b)

[1 2 3]


numpy.ndarray

In [17]:
c = np.array([1,2,3])
print(c)
type(c)

[1 2 3]


numpy.ndarray

In [18]:
d = torch.from_numpy(c)
print(d)
type(d)

tensor([1, 2, 3])


torch.Tensor