<a href="https://colab.research.google.com/github/Imrantipu/-serviceReviewServer/blob/main/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.version.cuda)


2.5.1+cu121
False
12.1


#Creating a Tensor

In [79]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[ 1.7086e-32,  0.0000e+00, -4.6056e+06],
        [ 4.3754e-41, -4.4800e+06,  4.3754e-41]])


In [80]:
# check type
print(a.dtype)
type(a)

torch.float32


torch.Tensor

In [81]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [82]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [83]:
# using rand generates 0-1 float values
torch.rand(2,3)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [84]:
# use of seed for same random values again
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [85]:
# using tensor for custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [86]:
from math import prod
# Other ways
# arange
print("using arange ->", torch.arange(0,10,2))
#using linspace
print("using linspace ->", torch.linspace(0,10,10))
# using eye for identity matrix
print("using eye ->", torch.eye(5))
#using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor shapes

In [87]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

torch.Size([2, 3])


In [88]:
# produce tensor like same shape of  existing one
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [89]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [90]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [91]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Tensor data type

In [92]:
# find data type
x.dtype

torch.int64

In [93]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [94]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathmatical operation

##1.Scaler operation

In [95]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [96]:
#addition
x+2
# substraction
x-2
# multiplication
x*2
# division
x/2
# int division
x//2
# power
x**2
#mod
x%2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

##2. Element wise operation

In [97]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [98]:
# add
a + b
# sustraction
a -b
# multiplication
a**b
# division
a/b
# power
a**b
# mod
a%b


tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [99]:
c = torch.tensor([1,-2,3,-4])

In [100]:
# absulute
torch.abs(c)

tensor([1, 2, 3, 4])

In [101]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [102]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [103]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [104]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [105]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [106]:
# less then 2 will be 2 and bigger then 3 will be 3
torch.clamp(d,min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

##3. Reduction operation

In [107]:
e = torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)
print(e)

tensor([[8., 0., 7.],
        [0., 0., 9.]])


In [108]:
# sum
torch.sum(e)

tensor(24.)

In [109]:
# sum along columns
torch.sum(e, dim = 0)

tensor([ 8.,  0., 16.])

In [110]:
#sum along rows
torch.sum(e, dim = 1)

tensor([15.,  9.])

In [111]:
#mean
torch.mean(e)

tensor(4.)

In [112]:
# mean along columns
torch.mean(e, dim = 0)

tensor([4., 0., 8.])

In [113]:
# median
torch.median(e)

tensor(0.)

In [114]:
# max
torch.max(e)

tensor(9.)

In [115]:
#min
torch.min(e)

tensor(0.)

In [116]:
# Product
torch.prod(e)

tensor(0.)

In [117]:
# variance
torch.var(e)

tensor(19.6000)

In [118]:
# stardard deviation
torch.std(e)

tensor(4.4272)

In [119]:
#argmax for maximum value position
torch.argmax(e)

tensor(5)

In [120]:
# argmin
torch.argmin(e)

tensor(1)

##4. Matrix operation

In [121]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [122]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [123]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
# dot product
torch.dot(vector1,vector2)

tensor(11)

In [124]:
# transpose
print(f)
torch.transpose(f,0,1)

tensor([[5, 7, 3],
        [9, 4, 0]])


tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [125]:
h = torch.randint(size=(3,3), low =0, high=10, dtype=torch.float32)
print(h)

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])


In [126]:
#determinant
torch.det(h)

tensor(-110.)

In [127]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

##5.Comparison operations

In [128]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [129]:
# grater then
print(i > j)
# less then
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)



tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


##6. Special function

In [130]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])


In [131]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [132]:
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [133]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [134]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [135]:
torch.softmax(k, dim = 0) # for columns

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [136]:
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace operation

In [137]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [138]:
# after operation result store in one operand
print(m.add_(n)) # permanent change happend in m
n.relu_() # permanent change happend in n


tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])


tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

## copy a tensor

In [139]:
a = torch.rand(2,3)
print(a)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [140]:
b = a.clone()
print(b)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
